name: empresta_app_mobile
description: Test mobile of Iago
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.14
  equatable: ^2.0.7
  dio: ^5.8.0+1
  gap: ^3.0.1

  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  flutter_masked_text2: ^0.9.1
  flutter_modular: ^6.3.4
  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.11
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  multi_dropdown: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/empresta.png"
  adaptive_icon_foreground: "assets/images/empresta.png"
  adaptive_icon_background: "#ef7d0a"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
