name: empresta_app_mobile
description: "Test mobile of Iago"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  flutter_masked_text2: ^0.9.1
  flutter_modular: ^6.3.4
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
